networks:
  servicediscovery:
    driver: overlay
    attachable: true

services:
  dockerswarm_sd_server:
    image: socheatsok78/dockerswarm_sd_server:latest
    networks:
      - servicediscovery
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager
