networks:
  dockerswarm_sd_network:
    name: dockerswarm_sd_network
    external: true

services:
  dockerswarm_sd_server:
    image: socheatsok78/dockerswarm_sd_server:main
    networks:
      - dockerswarm_sd_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
